CREATE TABLE fipe_dw.DIM_TIPO_MODELO(
	[COD_TIPO_MODELO]		[INT]			NOT NULL,
	[NME_TIPO_MODELO]		[varchar](8)	NULL,
	[DTA_INCLUSAO]			[datetime2](2)	NULL,
	[DTA_ATUALIZACAO]		[datetime2](2)	NULL, 
	[IND_ATIVO]				[bit]			NULL, 
	CONSTRAINT PK_DIM_TIPO_MODELO PRIMARY KEY(COD_TIPO_MODELO)
)
GO
ALTER TABLE fipe_dw.DIM_TIPO_MODELO
	ADD  CONSTRAINT [DF_DIM_TIPO_MODELO_DTA_INCLUSAO]  DEFAULT (GETDATE()) FOR [DTA_INCLUSAO]
GO
ALTER TABLE fipe_dw.DIM_TIPO_MODELO
	ADD  CONSTRAINT [DF_DIM_TIPO_MODELO_IND_ATIVO]  DEFAULT (0) FOR IND_ATIVO
