CREATE TABLE fipe_dw.DIM_TIPO_COMBUSTIVEL(
	[COD_TIPO_COMBUSTIVEL]		[INT]			NOT NULL,
	[NME_TIPO_COMBUSTIVEL]		[varchar](8)	NULL,
	[DTA_INCLUSAO]				[datetime2](2)	NULL,
	[DTA_ATUALIZACAO]			[datetime2](2)	NULL, 
	[IND_ATIVO]					[bit]			NULL, 
	CONSTRAINT PK_DIM_TIPO_COMBUSTIVEL PRIMARY KEY(COD_TIPO_COMBUSTIVEL)
)
GO
ALTER TABLE fipe_dw.DIM_TIPO_COMBUSTIVEL
	ADD  CONSTRAINT [DF_DIM_TIPO_COMBUSTIVEL_DTA_INCLUSAO]  DEFAULT (GETDATE()) FOR [DTA_INCLUSAO]
GO
ALTER TABLE fipe_dw.DIM_TIPO_COMBUSTIVEL
	ADD  CONSTRAINT [DF_DIM_TIPO_COMBUSTIVEL_IND_ATIVO]  DEFAULT (0) FOR IND_ATIVO