CREATE TABLE fipe_dw.DIM_TEMPO_MENSAL(
	[COD_MES_REFERENCIA]	[int]			NOT NULL,
	[NME_MES_REFERENCIA]	[varchar](30)	NULL,
	[COD_TRIMESTRE]			[int]			NULL,
	[NME_TRIMESTRE]			[varchar](12)	NULL,
	[COD_SEMESTRE]			[int]			NULL,
	[NME_SEMESTRE]			[varchar](12)	NULL,
	[NUM_ANO]				[int]			NULL,
	[DTA_INCLUSAO]			[datetime2](2)  NULL,
	[DTA_ATUALIZACAO]		[datetime2](2)  NULL,
	[IND_ATIVO]				[bit]			NULL, 
	CONSTRAINT PK_DIM_TEMPO_MENSAL PRIMARY KEY([COD_MES_REFERENCIA])
)
GO
ALTER TABLE fipe_dw.DIM_TEMPO_MENSAL
	ADD  CONSTRAINT [DF_DIM_TEMPO_MENSAL_DTA_INCLUSAO]  DEFAULT (GETDATE()) FOR [DTA_INCLUSAO]
GO
ALTER TABLE fipe_dw.DIM_TEMPO_MENSAL
	ADD  CONSTRAINT [DF_DIM_TEMPO_MENSAL_IND_ATIVO]  DEFAULT (0) FOR IND_ATIVO