CREATE TABLE fipe_dw.FTO_DADOS_MODELO (
	[SK_TEMPO]				[int] NULL,
	[COD_MODELO]			[int] NULL,
	[COD_MARCA]				[int] NULL,
	[COD_TIPO_VEICULO]		[int] NULL,
	[COD_TIPO_COMBUSTIVEL]	[int] NULL,
	[NUM_ANO_MODELO]		[int] NULL,
	[VLR_MODELO]			[money]	NULL,
	[DTA_INCLUSAO]			[datetime2](2) NULL,
	[DTA_ATUALIZACAO]		[datetime2](2) NULL, 
	CONSTRAINT FK_FTO_DADOS_MODELO_TIPO_VEICULO FOREIGN KEY  (COD_TIPO_VEICULO) REFERENCES fipe_dw.DIM_TIPO_MODELO (COD_TIPO_modelo)
)