CREATE TABLE [fipe].[ODS_MODELO](
	[COD_MODELO]			[int]			NOT NULL,
	[NME_MODELO]			[varchar](50)	NULL,
	[COD_TIPO_VEICULO]		[int]			NULL,
	[COD_MARCA]				[int]			NULL,
	[COD_FIPE]				[varchar](10)	NULL,
	[DTA_INCLUSAO]			[datetime2](2)	NULL,
	[DTA_ATUALIZACAO]		[datetime2](2)	NULL, 
	CONSTRAINT PK_ODS_MODELO PRIMARY KEY (COD_MODELO), 
	CONSTRAINT FK_ODS_MODELO_MARCA FOREIGN KEY (COD_MARCA) REFERENCES fipe.ODS_MARCA (COD_MARCA)
) ON [PRIMARY]
GO
ALTER TABLE [fipe].[ODS_MODELO]
  ADD CONSTRAINT [DF_ODS_MODELO_DTA_INCLUSAO] DEFAULT (getdate())   FOR [DTA_INCLUSAO]    

