CREATE TABLE [fipe].[ODS_MES_REFERENCIA](
	[COD_MES_REFERENCIA] [int]			NOT NULL,
	[NME_MES_REFERENCIA] [varchar](20)	NULL,
	[DTA_INCLUSAO] [datetime2](2)		NULL, 
	[DTA_ATUALIZACAO] [datetime2](2)	NULL,
	CONSTRAINT PK_ODS_MES_REFERENCIA PRIMARY KEY (COD_MES_REFERENCIA)
) ;
GO
ALTER TABLE [fipe].[ODS_MES_REFERENCIA] 
    ADD CONSTRAINT [DF_ODS_MES_REFERENCIA_DTA_INCLUSAO] DEFAULT (getdate()) FOR DTA_INCLUSAO

