CREATE TABLE [fipe].[STG_MARCA] (
    [COD_MARCA]          INT           NULL,
    [NME_MARCA]          VARCHAR (30)  NULL,
    [COD_TIPO_VEICULO]   INT           NULL,
    [COD_MES_REFERENCIA] INT           NULL,
    [DTA_INCLUSAO]       DATETIME2 (2) CONSTRAINT [DF_STG_MARCA_DTA_INCLUSAO] DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IXC_STG_MARCA]
    ON [fipe].[STG_MARCA]([COD_MARCA] ASC, [COD_TIPO_VEICULO] ASC);

