CREATE TABLE [fipe].[STG_MODELO] (
    [COD_MODELO]         INT           NULL,
    [NME_MODELO]         VARCHAR (50)  NULL,
    [COD_TIPO_VEICULO]   INT           NULL,
    [COD_MES_REFERENCIA] INT           NULL,
    [COD_MARCA]          INT           NULL,
    [DTA_INCLUSAO]       DATETIME2 (2) CONSTRAINT [DF_STG_MODELO_DTA_INCLUSAO] DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IXC_STG_MODELO]
    ON [fipe].[STG_MODELO]([COD_MODELO] ASC, [COD_MARCA] ASC, [COD_TIPO_VEICULO] ASC);

