CREATE TABLE [fipe].[STG_MES_REFERENCIA] (
    [COD_MES_REFERENCIA] INT           NULL,
    [NME_MES_REFERENCIA] VARCHAR (20)  NULL,
    [DTA_INCLUSAO]       DATETIME2 (2) CONSTRAINT [DF_STG_MES_REFERENCIA_DTA_INCLUSAO] DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IXC_STG_MES_REFERENCIA]
    ON [fipe].[STG_MES_REFERENCIA]([COD_MES_REFERENCIA] ASC);

