
-- FIPE_ODS.SP_ODS_CONTROLE

CREATE  PROCEDURE FIPE_ODS.SP_ODS_CONTROLE
AS
BEGIN
	EXEC [fipe_ods].[SP_ODS_MES_REFERENCIA]
	EXEC [fipe_ods].[SP_ODS_UNIDADE_FEDERATIVA]
	EXEC [fipe_ods].[SP_ODS_MARCA] 
	EXEC [fipe_ods].[SP_ODS_MODELO]
	EXEC [fipe_ods].[SP_ODS_DADOS_MODELO]
END