CREATE  PROCEDURE [fipe_ods].[SP_ODS_UNIDADE_FEDERATIVA] AS 
BEGIN 

	TRUNCATE TABLE [fipe_ods].[ODS_UNIDADE_FEDERATIVA]

	INSERT INTO [fipe_ods].[ODS_UNIDADE_FEDERATIVA]
	(
		  COD_UF
		, NME_UF
		, SGL_UF
		, COD_REGIAO
		, DTA_INCLUSAO
	)
	SELECT	
		STG.COD_UF, 
		STG.NME_UF, 
		STG.SGL_UF, 
		RG.COD_REGIAO,
		GETDATE()
	FROM [FIPE_STG].[STG_UNIDADE_FEDERATIVA] STG 
	INNER JOIN 
		fipe_ods.ODS_REGIAO  RG
	ON STG.NME_REGIAO	= RG.NME_REGIAO

END