
CREATE PROCEDURE FIPE_ODS.SP_ODS_UNIDADE_FEDERATIVA AS 
BEGIN 

	TRUNCATE TABLE [fipe_ods].[ODS_UNIDADE_FEDERATIVA]

	INSERT INTO [fipe_ods].[ODS_UNIDADE_FEDERATIVA]
	(
		COD_UF
		,SGL_UF
		,SGL_ISO3166_2
		,NME_UF
		,DSC_URL_WEBSITE
		,DSC_URL_BANDEIRA
		,COD_REGIAO
	)
	SELECT	
		STG.UF, 
		STG.UF_CODE, 
		STG.ISO3166_2, 
		STG.NAME, 
		STG.WEBSITE, 
		STG.FLAG_IMAGE, 
		RG.COD_REGIAO
	FROM [FIPE_STG].[STG_UNIDADE_FEDERATIVA] STG 
	INNER JOIN 
		fipe_ods.ODS_REGIAO_UF  RG
	ON STG.macroregion	= RG.NME_REGIAO

END