CREATE TABLE [fipe_stg].[STG_UNIDADE_FEDERATIVA] (
    [COD_UF]       SMALLINT      NOT NULL,
    [NME_UF]       VARCHAR (30)  NULL,
    [SGL_UF]       VARCHAR (2)   NULL,
    [DTA_INCLUSAO] DATETIME2 (2) CONSTRAINT [DF_STG_UNIDADE_FEDERATIVA] DEFAULT (getdate()) NULL,
    [NME_REGIAO]   VARCHAR (50)  NULL
);



