CREATE TABLE [fipe_ods].[ODS_REGIAO] (
    [COD_REGIAO]   TINYINT       NOT NULL,
    [NME_REGIAO]   VARCHAR (20)  NULL,
    [SGL_REGIAO]   VARCHAR (2)   NULL,
    [DTA_INCLUSAO] DATETIME2 (2) CONSTRAINT [DF_ODS_REGIAO] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ODS_REGIAO_UF] PRIMARY KEY CLUSTERED ([COD_REGIAO] ASC)
);

