CREATE PROCEDURE fipe.SP_ODS_MES_REFERENCIA
AS
BEGIN
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	MERGE INTO fipe.ODS_MES_REFERENCIA WITH (TABLOCK) AS DESTINO
		USING (											
				SELECT 
					 COD_MES_REFERENCIA
					,NME_MES_REFERENCIA
					,DTA_INCLUSAO
				FROM  fipe.STG_MES_REFERENCIA (NOLOCK)
			   ) AS ORIGEM
	ON 
		(
			DESTINO.COD_MES_REFERENCIA	=	ORIGEM.COD_MES_REFERENCIA
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 COD_MES_REFERENCIA
				,NME_MES_REFERENCIA
				,DTA_INCLUSAO
			)	
			VALUES
			(	
				 ORIGEM.COD_MES_REFERENCIA
				,ORIGEM.NME_MES_REFERENCIA
				,@DTA_EXECUCAO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NME_MES_REFERENCIA	<>	DESTINO.NME_MES_REFERENCIA	OR	(ORIGEM.NME_MES_REFERENCIA	IS NULL AND DESTINO.NME_MES_REFERENCIA	IS NOT NULL)	OR	(ORIGEM.NME_MES_REFERENCIA	IS NOT NULL AND DESTINO.NME_MES_REFERENCIA	IS NULL))	
	)
	THEN UPDATE
		SET
			DESTINO.NME_MES_REFERENCIA	= 	ORIGEM.NME_MES_REFERENCIA,
			DESTINO.DTA_ATUALIZACAO		=	@DTA_EXECUCAO 
	;	
END