CREATE VIEW [fipe_dw].[VW_DIM_TIPO_COMBUSTIVEL]
AS
	SELECT COD_TIPO_COMBUSTIVEL, NME_TIPO_COMBUSTIVEL , SGL_TIPO_COMBUSTIVEL
		FROM (
				VALUES	(1, 'Gasolina', 'G'), 
						(2, 'Álcool', 'A'), 
						(3, 'Diesel', 'D'),
						(4, 'Elétrico', 'E'),
						(5, 'Híbrido', 'H')
			) as DIM_TIPO_COMBUSTIVEL (COD_TIPO_COMBUSTIVEL, NME_TIPO_COMBUSTIVEL , SGL_TIPO_COMBUSTIVEL)
