CREATE PROCEDURE [fipe_dw].[SP_DW_FTO_INDICE_PRECO] 
	@COD_ANO_MES INT = NULL
-- 	@FLG_REPROCESSAMENTO BIT 
AS 
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()

	--IF @COD_ANO_MES IS NULL AND @FLG_REPROCESSAMENTO = 0 
		/*proximo mes que ainda não foi processado */
		-- SET @COD_ANO_MES =  (SELECT LEFT(FORMAT(DATEADD(MM, 1, CAST(CONCAT(MAX(COD_ANO_MES), '01') AS DATE)), 'yyyyMMdd'), 6) 
		-- 						FROM fipe_dw.DW_DIM_TEMPO_MENSAL WHERE FLG_ATIVO = 1 )
	
	/*IPCA - índice geral*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7169' /*indice geral*/
	)
	SELECT 
		COD_ANO_MES					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
		into #DW_FTO_INDICE_PRECO
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	
	CREATE CLUSTERED INDEX IXC_DW_FTO_INDICE_PRECO ON #DW_FTO_INDICE_PRECO (COD_ANO_MES, COD_INDICADOR,	COD_INDICADOR_ITEM)

	/*IPCA - 5102009.Acessórios e peças*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7645' /*5102009.Acessórios e peças*/
	)
	INSERT INTO #DW_FTO_INDICE_PRECO
	(
		  COD_ANO_MES
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_ANO_MES					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	

	/*IPCA - 5102011.Conserto de automóvel*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7647' /*5102009.Acessórios e peças*/
	)
	INSERT INTO #DW_FTO_INDICE_PRECO
	(
		  COD_ANO_MES
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_ANO_MES					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	
	/*INPC - índice geral*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7169' /*indice geral*/			
	)
	INSERT INTO #DW_FTO_INDICE_PRECO
	(
		  COD_ANO_MES
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_ANO_MES					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	

	/*INPC - 5102009.Acessórios e peças*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7645' /*5102009.Acessórios e peças*/
	)
	INSERT INTO #DW_FTO_INDICE_PRECO 
	(
		  COD_ANO_MES
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_ANO_MES					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	

	
	/*INPC - 5102011.Conserto de automóvel*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					 TEMPO.COD_ANO_MES,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.COD_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7647' /*5102009.Acessórios e peças*/
	)
	INSERT INTO #DW_FTO_INDICE_PRECO 
	(
		  COD_ANO_MES
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_ANO_MES					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	


	MERGE INTO fipe_dw.DW_FTO_INDICE_PRECO WITH (TABLOCK) AS DESTINO
		USING (													
			SELECT 
					  COD_ANO_MES
					, COD_INDICADOR
					, COD_INDICADOR_ITEM
					, VLR_INDICE_VAR_MES
					, VLR_INDICE_ACM_ANO
					, VLR_INDICE_ACM_12M
			FROM #DW_FTO_INDICE_PRECO
			/* carrega os dados do mes passado como parametro ou todos os meses se estiver nulo*/
			WHERE (COD_ANO_MES = @COD_ANO_MES and  @COD_ANO_MES  IS NOT NULL) OR @COD_ANO_MES  IS NULL

		) AS ORIGEM
	ON 
		(
			DESTINO.cod_ano_mes			= ORIGEM.COD_ANO_MES		AND		 
			DESTINO.COD_INDICADOR			= ORIGEM.COD_INDICADOR		AND 
			DESTINO.COD_INDICADOR_ITEM		= ORIGEM.COD_INDICADOR_ITEM
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				  cod_ano_mes
				, COD_INDICADOR
				, COD_INDICADOR_ITEM
				, VLR_INDICE_VAR_MES
				, VLR_INDICE_ACM_ANO
				, VLR_INDICE_ACM_12M
				, DTA_INCLUSAO
			)	
			VALUES
			(	
				 ORIGEM.COD_ANO_MES
				,ORIGEM.COD_INDICADOR
				,ORIGEM.COD_INDICADOR_ITEM
				,ORIGEM.VLR_INDICE_VAR_MES
				,ORIGEM.VLR_INDICE_ACM_ANO
				,ORIGEM.VLR_INDICE_ACM_12M
				,@DTA_EXECUCAO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.VLR_INDICE_VAR_MES	<>	DESTINO.VLR_INDICE_VAR_MES	OR	(ORIGEM.VLR_INDICE_VAR_MES	IS NULL AND DESTINO.VLR_INDICE_VAR_MES	IS NOT NULL)	OR	(ORIGEM.VLR_INDICE_VAR_MES	IS NOT NULL AND DESTINO.VLR_INDICE_VAR_MES	IS NULL))	OR
		(ORIGEM.VLR_INDICE_ACM_ANO	<>	DESTINO.VLR_INDICE_ACM_ANO	OR	(ORIGEM.VLR_INDICE_ACM_ANO	IS NULL AND DESTINO.VLR_INDICE_ACM_ANO	IS NOT NULL)	OR	(ORIGEM.VLR_INDICE_ACM_ANO	IS NOT NULL AND DESTINO.VLR_INDICE_ACM_ANO	IS NULL))	OR 
		(ORIGEM.VLR_INDICE_ACM_12M	<>	DESTINO.VLR_INDICE_ACM_12M	OR	(ORIGEM.VLR_INDICE_ACM_12M	IS NULL AND DESTINO.VLR_INDICE_ACM_12M	IS NOT NULL)	OR	(ORIGEM.VLR_INDICE_ACM_12M	IS NOT NULL AND DESTINO.VLR_INDICE_ACM_12M	IS NULL))		
	)
	THEN UPDATE
		SET
			DESTINO.VLR_INDICE_VAR_MES	= 	ORIGEM.VLR_INDICE_VAR_MES	,
			DESTINO.VLR_INDICE_ACM_ANO	= 	ORIGEM.VLR_INDICE_ACM_ANO	,
			DESTINO.VLR_INDICE_ACM_12M	= 	ORIGEM.VLR_INDICE_ACM_12M	,
			DESTINO.DTA_ATUALIZACAO		=	@DTA_EXECUCAO 						
	;	
END