CREATE PROCEDURE [fipe_dw].[SP_DW_DIM_MODELO]
AS
BEGIN
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	MERGE INTO FIPE_DW.DW_DIM_MODELO WITH (TABLOCK) AS DESTINO
		USING (											
			SELECT 
				 MD.COD_MODELO
				,MD.NME_MODELO
				,MD.COD_FIPE
				,MD.COD_TIPO_VEICULO
				,MC.COD_MARCA
				,MC.NME_MARCA
			FROM fipe_ods.ODS_MODELO MD (NOLOCK)
			inner join fipe_ods.ODS_MARCA MC (NOLOCK)
			ON MD.COD_MARCA = MC.COD_MARCA
		) AS ORIGEM
	ON 
		(
			DESTINO.COD_MODELO	=	ORIGEM.COD_MODELO
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 COD_MODELO
				,NME_MODELO
				,COD_FIPE
				,COD_TIPO_VEICULO
				,COD_MARCA
				,NME_MARCA
				,DTA_INCLUSAO
			)	
			VALUES
			(	
				 ORIGEM.COD_MODELO
				,ORIGEM.NME_MODELO
				,ORIGEM.COD_FIPE
				,ORIGEM.COD_TIPO_VEICULO
				,ORIGEM.COD_MARCA
				,ORIGEM.NME_MARCA
				,@DTA_EXECUCAO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NME_MODELO			<>	DESTINO.NME_MODELO			OR	(ORIGEM.NME_MODELO			IS NULL AND DESTINO.NME_MODELO			IS NOT NULL)	OR	(ORIGEM.NME_MODELO			IS NOT NULL AND DESTINO.NME_MODELO			IS NULL))	OR
		(ORIGEM.COD_FIPE			<>	DESTINO.COD_FIPE			OR	(ORIGEM.COD_FIPE			IS NULL AND DESTINO.COD_FIPE			IS NOT NULL)	OR	(ORIGEM.COD_FIPE			IS NOT NULL AND DESTINO.COD_FIPE			IS NULL))	OR 
		(ORIGEM.COD_TIPO_VEICULO	<>	DESTINO.COD_TIPO_VEICULO	OR	(ORIGEM.COD_TIPO_VEICULO	IS NULL AND DESTINO.COD_TIPO_VEICULO	IS NOT NULL)	OR	(ORIGEM.COD_TIPO_VEICULO	IS NOT NULL AND DESTINO.COD_TIPO_VEICULO	IS NULL))	OR 
		(ORIGEM.COD_MARCA			<>	DESTINO.COD_MARCA			OR	(ORIGEM.COD_MARCA			IS NULL AND DESTINO.COD_MARCA			IS NOT NULL)	OR	(ORIGEM.COD_MARCA			IS NOT NULL AND DESTINO.COD_MARCA			IS NULL))	OR
		(ORIGEM.NME_MARCA			<>	DESTINO.NME_MARCA			OR	(ORIGEM.NME_MARCA			IS NULL AND DESTINO.NME_MARCA			IS NOT NULL)	OR	(ORIGEM.NME_MARCA			IS NOT NULL AND DESTINO.NME_MARCA			IS NULL))	
	)
	THEN UPDATE
		SET
			DESTINO.NME_MODELO			= 	ORIGEM.NME_MODELO			,
			DESTINO.COD_FIPE			= 	ORIGEM.COD_FIPE				,
			DESTINO.COD_TIPO_VEICULO	= 	ORIGEM.COD_TIPO_VEICULO		,
			DESTINO.COD_MARCA			= 	ORIGEM.COD_MARCA			,
			DESTINO.NME_MARCA			= 	ORIGEM.NME_MARCA			,
			DESTINO.DTA_ATUALIZACAO		=	@DTA_EXECUCAO 
	;	
END