CREATE PROCEDURE [FIPE_DW].[SP_DW_DIM_REGIAO]
 AS 
 BEGIN 
	-- TROCAR TRUNCATE/INSERT PARA MERGE
	TRUNCATE TABLE [fipe_dw].[DW_DIM_REGIAO]
	insert into [fipe_dw].[DW_DIM_REGIAO]
	(
			COD_UF
		, NME_UF
		, SGL_UF
		, COD_REGIAO
		, NME_REGIAO
	)
	SELECT COD_UF, NME_UF, SGL_UF, RG.COD_REGIAO, RG.NME_REGIAO
	FROM [fipe_ods].[ODS_UNIDADE_FEDERATIVA] UF 
	INNER JOIN fipe_ods.ODS_REGIAO RG
	ON UF.COD_REGIAO =  RG.COD_REGIAO
END