 CREATE     PROCEDURE [fipe_dw].[SP_DW_DIM_TEMPO_MENSAL]
AS
BEGIN
	SET LANGUAGE Portuguese
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	DROP TABLE IF EXISTS #DW_CADASTRO_MES
	SELECT NUM_MES, NME_MES  INTO #DW_CADASTRO_MES
		FROM (
				VALUES	(1,		'janeiro'	), 
						(2,		'fevereiro'	), 
						(3,		'março'		),
						(4,		'abril'		),
						(5,		'maio'		),
						(6,		'junho'		),
						(7,		'julho'		),
						(8,		'agosto'	),
						(9,		'setembro'	),
						(10,	'outubro'	),
						(11,	'novembro'	),
						(12,	'dezembro'	)
			) AS DW_CADASTRO_MES (NUM_MES, NME_MES)

	DROP TABLE IF EXISTS #ODS_CADASTRO_MES_REFERENCIA
  	SELECT	COD_MES_REFERENCIA,
			NME_MES_REFERENCIA,
			CONCAT(NUM_ANO, RIGHT('0' + CAST(NUM_MES AS VARCHAR(2)), 2)) COD_ANO_MES
		INTO #ODS_CADASTRO_MES_REFERENCIA
	from fipe_ods.ODS_MES_REFERENCIA 
	CREATE CLUSTERED INDEX IXC_ODS_CADASTRO_MES_REFERENCIA ON #ODS_CADASTRO_MES_REFERENCIA (COD_MES_REFERENCIA)
	
	
	MERGE INTO fipe_dw.DW_DIM_TEMPO_MENSAL WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT 
						COD_ANO_MES,
						COD_MES_REFERENCIA COD_MES_REFERENCIA_FIPE
				FROM  #ODS_CADASTRO_MES_REFERENCIA (NOLOCK)
			) AS ORIGEM
	ON 	(	
			DESTINO.COD_ANO_MES		=	ORIGEM.COD_ANO_MES	
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				COD_ANO_MES,
				COD_MES_REFERENCIA_FIPE,
				DTA_INCLUSAO
			)	
			VALUES
			(	
				ORIGEM.COD_ANO_MES
				,ORIGEM.COD_MES_REFERENCIA_FIPE		
				,@DTA_EXECUCAO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.COD_MES_REFERENCIA_FIPE	<>	DESTINO.COD_MES_REFERENCIA_FIPE	OR	(ORIGEM.COD_MES_REFERENCIA_FIPE	IS NULL AND DESTINO.COD_MES_REFERENCIA_FIPE	IS NOT NULL)	OR	(ORIGEM.COD_MES_REFERENCIA_FIPE	IS NOT NULL AND DESTINO.COD_MES_REFERENCIA_FIPE	IS NULL))		
	)
	THEN UPDATE
		SET
			DESTINO.COD_MES_REFERENCIA_FIPE	=	ORIGEM.COD_MES_REFERENCIA_FIPE, 
			DESTINO.DTA_ATUALIZACAO			=	@DTA_EXECUCAO 
	;	
END