CREATE PROCEDURE [fipe_dw].[SP_DW_FTO_INDICE_PRECO] 
AS 

BEGIN 
	/*TROCAR TRUNCATE POR MERGE*/
	TRUNCATE TABLE [fipe_dw].[DW_FTO_INDICE_PRECO] 

	/*IPCA - índice geral*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7169' /*indice geral*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	

	/*IPCA - 5102009.Acessórios e peças*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7645' /*5102009.Acessórios e peças*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	


	/*IPCA - 5102011.Conserto de automóvel*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('IPCA', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7647' /*5102009.Acessórios e peças*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		1 COD_INDICADOR,/*IPCA*/
		COD_INDICADOR_ITEM,
		[63]			VLR_INDICE_VAR_MES	,
		[69]			VLR_INDICE_ACM_ANO	,
		[2265]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([63],[69],[2265])) AS P
	



	/*INPC - índice geral*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7169' /*indice geral*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	

	/*INPC - 5102009.Acessórios e peças*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7645' /*5102009.Acessórios e peças*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	

	
	/*INPC - 5102011.Conserto de automóvel*/
	; WITH STG_INDICE_PRECO AS (
		SELECT ISNULL(TRY_CAST(V AS FLOAT), 0)VLR_INDICADOR, 
					TEMPO.COD_MES_REFERENCIA,
					--D2N DSC_INDICADOR,
					D2C COD_VARIAVEL ,
					D4C COD_INDICADOR_ITEM
				FROM FIPE_STG.STG_INDICADOR_SIDRA IND 
				INNER JOIN FIPE_DW.DW_DIM_TEMPO_MENSAL TEMPO
				ON IND.D3C = TEMPO.NUM_ANO_MES
				WHERE CHARINDEX('INPC', D2N ) > 0
				AND CHARINDEX('BRASIL', D1N ) > 0
				and d4c = '7647' /*5102009.Acessórios e peças*/
	)
	INSERT INTO [fipe_dw].[DW_FTO_INDICE_PRECO] 
	(
		  COD_MES_REFERENCIA
		, COD_INDICADOR
		, COD_INDICADOR_ITEM
		, VLR_INDICE_VAR_MES
		, VLR_INDICE_ACM_ANO
		, VLR_INDICE_ACM_12M
	)
	SELECT 
		COD_MES_REFERENCIA					, 	
		2 COD_INDICADOR,/*INPC*/
		COD_INDICADOR_ITEM,
		[44]			VLR_INDICE_VAR_MES	,
		[68]			VLR_INDICE_ACM_ANO	,
		[2292]			VLR_INDICE_ACM_12M	
	FROM STG_INDICE_PRECO STG							
	PIVOT(MAX(VLR_INDICADOR) 
	FOR COD_VARIAVEL IN ([44],[68],[2292])) AS P
	
END