CREATE   PROCEDURE [fipe_dw].[SP_DW_FTO_CRIME_VEICULO]
AS
BEGIN

	DROP TABLE IF EXISTS #INDICADOR_ROUBO
	; WITH STG_ROUBO AS (
	SELECT UF.COD_UF, 
		UF.NME_UF, 
		TIPO_CRIME, 
		ANO, 
		MES, 
		QTD_OCORRENCIA 
		FROM fipe_stg.STG_INDICADOR_SEGURANCA SG
	INNER JOIN fipe_ods.ODS_UNIDADE_FEDERATIVA UF 
	ON SG.UF =  UF.NME_UF
	WHERE TIPO_CRIME IN ('Furto de veículo', 'Roubo de veículo')
	) SELECT 
		COD_UF, 
		ANO, 
		MES,
		[Furto de veículo]	QTD_FURTO, 
		[Roubo de veículo]	QTD_ROUBO
	INTO #TMP_CRIME_VEICULO
	FROM STG_ROUBO STG
	PIVOT(SUM(QTD_OCORRENCIA) FOR TIPO_CRIME IN ([Furto de veículo], [Roubo de veículo])) AS P

	CREATE CLUSTERED INDEX IXC_CRIME_VEICULO ON #TMP_CRIME_VEICULO (COD_UF, ANO, MES)
	TRUNCATE TABLE [fipe_dw].[DW_FTO_CRIME_VEICULO]
	INSERT INTO [fipe_dw].[DW_FTO_CRIME_VEICULO]
		(
			  COD_UF
			, COD_MES_REFERENCIA
			, QTD_FURTO
			, QTD_ROUBO
		)
	SELECT 
			STG.COD_UF, 
			TEMPO.COD_MES_REFERENCIA,
			STG.QTD_FURTO, 
			STG.QTD_ROUBO
	FROM #TMP_CRIME_VEICULO STG
	INNER JOIN fipe_dw.DW_DIM_TEMPO_MENSAL TEMPO
		ON	STG.ANO = TEMPO.NUM_ANO AND 
			STG.MES = TEMPO.NME_MES 	
END