CREATE   PROCEDURE [fipe_ods].[SP_ODS_MODELO]
AS
BEGIN
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	MERGE INTO fipe_ods.ODS_MODELO WITH (TABLOCK) AS DESTINO
		USING (											
			SELECT DISTINCT 
				 COD_MODELO
				,NME_MODELO
				,COD_TIPO_VEICULO
				,COD_MARCA
			FROM  fipe_stg.STG_MODELO (NOLOCK)
			   ) AS ORIGEM
	ON 
		(
			DESTINO.COD_MODELO	=	ORIGEM.COD_MODELO
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 COD_MODELO
				,NME_MODELO
				,COD_TIPO_VEICULO
				,COD_MARCA
				,DTA_INCLUSAO
			)	
			VALUES
			(	
				 ORIGEM.COD_MODELO
				,ORIGEM.NME_MODELO
				,ORIGEM.COD_TIPO_VEICULO
				,ORIGEM.COD_MARCA
				,@DTA_EXECUCAO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NME_MODELO			<>	DESTINO.NME_MODELO			OR	(ORIGEM.NME_MODELO			IS NULL AND DESTINO.NME_MODELO			IS NOT NULL)	OR	(ORIGEM.NME_MODELO			IS NOT NULL AND DESTINO.NME_MODELO			IS NULL))	OR
		(ORIGEM.COD_TIPO_VEICULO	<>	DESTINO.COD_TIPO_VEICULO	OR	(ORIGEM.COD_TIPO_VEICULO	IS NULL AND DESTINO.COD_TIPO_VEICULO	IS NOT NULL)	OR	(ORIGEM.COD_TIPO_VEICULO	IS NOT NULL AND DESTINO.COD_TIPO_VEICULO	IS NULL))	OR 
		(ORIGEM.COD_MARCA			<>	DESTINO.COD_MARCA			OR	(ORIGEM.COD_MARCA			IS NULL AND DESTINO.COD_MARCA			IS NOT NULL)	OR	(ORIGEM.COD_MARCA			IS NOT NULL AND DESTINO.COD_MARCA			IS NULL))	
	)
	THEN UPDATE
		SET
			DESTINO.NME_MODELO			= 	ORIGEM.NME_MODELO			,
			DESTINO.COD_TIPO_VEICULO	= 	ORIGEM.COD_TIPO_VEICULO		,
			DESTINO.COD_MARCA			= 	ORIGEM.COD_MARCA			,
			DESTINO.DTA_ATUALIZACAO		=	@DTA_EXECUCAO 
	;	

	/*Leitura de código fipe que veio da tabela de dados do modelo*/
	UPDATE M SET M.COD_FIPE = DM.COD_FIPE 
	FROM fipe_ods.ODS_MODELO M 
	INNER JOIN (
				SELECT DISTINCT COD_MODELO, COD_FIPE
					FROM fipe_stg.STG_DADOS_MODELO
				) DM
	ON M.COD_MODELO = DM.COD_MODELO
	WHERE M.COD_FIPE IS NULL
END
