CREATE TABLE [fipe_dw].[DW_DIM_REGIAO] (
    [COD_UF]          SMALLINT      NOT NULL,
    [NME_UF]          VARCHAR (30)  NULL,
    [SGL_UF]          VARCHAR (2)   NULL,
    [COD_REGIAO]      TINYINT       NULL,
    [NME_REGIAO]      VARCHAR (20)  NULL,
    [DTA_INCLUSAO]    DATETIME2 (2) CONSTRAINT [DF_DTA_INCLUSAO] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO] DATETIME      NULL,
    CONSTRAINT [PK_DIM_REGIAO] PRIMARY KEY CLUSTERED ([COD_UF] ASC)
);



