CREATE TABLE fipe_dw.DW_DIM_MODELO (
	[COD_MODELO]			[int]			NOT NULL,
	[NME_MODELO]			[varchar](50)	NULL,
	[COD_FIPE]				[varchar](10)	NULL,
	[COD_TIPO_VEICULO]		[tinyint]		NULL,
	[COD_MARCA]				[int]			NULL,
	[NME_MARCA]				[varchar](30)	NULL,
	[DTA_INCLUSAO]			[datetime2](2)	NULL,
	[DTA_ATUALIZACAO]		[datetime2](2)	NULL, 
	[FLG_ATIVO]				[bit]			NULL, 
	CONSTRAINT PK_DIM_MODELO PRIMARY KEY(COD_MODELO)
)
GO
ALTER table fipe_dw.DW_DIM_MODELO 
	ADD  CONSTRAINT [DF_DW_DIM_MODELO_DTA_INCLUSAO]  DEFAULT (getdate()) FOR [DTA_INCLUSAO]
GO
ALTER TABLE fipe_dw.DW_DIM_MODELO  
	ADD  CONSTRAINT [DF_DW_DIM_MODELO_FLG_ATIVO]  DEFAULT (0) FOR FLG_ATIVO