CREATE TABLE [fipe_dw].[DW_DIM_INDICADOR_ITEM] (
    [COD_INDICADOR_ITEM]		INT       NOT NULL,
	[COD_INDICADOR_EXTERNO]		VARCHAR(50)   NULL,
    [NME_INDICADOR_ITEM]		VARCHAR(50)   NULL,
	[NME_INDICADOR_ITEM_EXTERNO] AS CONCAT ([COD_INDICADOR_EXTERNO], '.', [NME_INDICADOR_ITEM]),
    [DTA_INCLUSAO]				DATETIME2 (2) CONSTRAINT [DF_DW_DIM_INDICADOR_ITEM] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO]			DATETIME2 (2) NULL,
    [FLG_ATIVO]					BIT           CONSTRAINT [DF_DW_DIM_INDICADOR_ITEM_FLG_ATIVO] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_DW_DIM_INDICADOR_ITEM] PRIMARY KEY CLUSTERED ([COD_INDICADOR_ITEM] ASC)
);

GO 

/*
-- dados de cadastro
INSERT [fipe_dw].[DW_DIM_INDICADOR_ITEM]
	(
		  COD_INDICADOR_ITEM
		, COD_INDICADOR_EXTERNO
		, NME_INDICADOR_ITEM
	)
values
		(7169, '0', 'Índice geral'), 
		(7645, '5102009', 'Acessórios e peças'), 
		(7647, '5102011', 'Conserto de automóvel')
*/