CREATE TABLE [fipe_dw].[DW_DIM_TIPO_COMBUSTIVEL] (
    [COD_TIPO_COMBUSTIVEL] TINYINT			NOT NULL,
    [NME_TIPO_COMBUSTIVEL] VARCHAR(20)		NULL,
    [SGL_TIPO_COMBUSTIVEL] CHAR (1)			NULL,
    [DTA_INCLUSAO]         DATETIME2(2)		CONSTRAINT [DF_DW_DIM_TIPO_COMBUSTIVEL_DTA_INCLUSAO] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO]      DATETIME2(2)		NULL,
    [FLG_ATIVO]            BIT				CONSTRAINT [DF_DW_DIM_TIPO_COMBUSTIVEL_FLG_ATIVO] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_DIM_TIPO_COMBUSTIVEL]	PRIMARY KEY CLUSTERED ([COD_TIPO_COMBUSTIVEL] ASC)
);


GO


/*
	INSERT INTO FIPE_DW.DW_DIM_TIPO_COMBUSTIVEL
	(
		  COD_TIPO_COMBUSTIVEL
		, NME_TIPO_COMBUSTIVEL
		, SGL_TIPO_COMBUSTIVEL
	)
	VALUES 
		(1, 'Gasolina', 'G'), 
		(2, 'Álcool', 'A'), 
		(3, 'Diesel', 'D'),
		(4, 'Elétrico', 'E'),
		(5, 'Híbrido', 'H'),
		(6, 'Flex', 'F')

*/