CREATE TABLE [fipe_dw].[DW_FTO_INDICE_PRECO] (
    [DTA_REFERENCIA]     INT           NOT NULL,
    [COD_INDICADOR]      TINYINT       NOT NULL,
    [COD_INDICADOR_ITEM] INT           NOT NULL,
    [VLR_INDICE_VAR_MES] FLOAT (53)    NULL,
    [VLR_INDICE_ACM_ANO] FLOAT (53)    NULL,
    [VLR_INDICE_ACM_12M] FLOAT (53)    NULL,
    [DTA_INCLUSAO]       DATETIME2 (2) CONSTRAINT [DF_DW_FTO_INDICE_PRECO_DTA_INCLUSAO] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO]    DATETIME2 (2) NULL,
    CONSTRAINT [PK_DW_FTO_INDICE_PRECO] PRIMARY KEY CLUSTERED ([DTA_REFERENCIA] ASC, [COD_INDICADOR] ASC, [COD_INDICADOR_ITEM] ASC),
    CONSTRAINT [FK_INDICE_PRECO_DIM_INDICADOR] FOREIGN KEY ([COD_INDICADOR]) REFERENCES [fipe_dw].[DW_DIM_INDICADOR] ([COD_INDICADOR]),
    CONSTRAINT [FK_INDICE_PRECO_DIM_INDICADOR_ITEM] FOREIGN KEY ([COD_INDICADOR_ITEM]) REFERENCES [fipe_dw].[DW_DIM_INDICADOR_ITEM] ([COD_INDICADOR_ITEM]),
    CONSTRAINT [FK_INDICE_PRECO_TEMPO] FOREIGN KEY ([DTA_REFERENCIA]) REFERENCES [fipe_dw].[DW_DIM_TEMPO_MENSAL] ([COD_ANO_MES])
);







