CREATE TABLE [fipe_dw].[DW_FTO_CRIME_VEICULO] (
    [COD_UF]          SMALLINT      NOT NULL,
    [COD_ANO_MES]     INT           NOT NULL,
    [QTD_FURTO]       INT           NULL,
    [QTD_ROUBO]       INT           NULL,
    [DTA_INCLUSAO]    DATETIME2 (2) CONSTRAINT [DF_DW_FTO_CRIME_VEICULO] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO] DATETIME2 (2) NULL,
    CONSTRAINT [FK_FTO_CRIME_REGIAO] FOREIGN KEY ([COD_UF]) REFERENCES [fipe_dw].[DW_DIM_REGIAO] ([COD_UF]),
    CONSTRAINT [FK_FTO_CRIME_TEMPO_MENSAL] FOREIGN KEY ([COD_ANO_MES]) REFERENCES [fipe_dw].[DW_DIM_TEMPO_MENSAL] ([COD_ANO_MES])
);








GO
CREATE CLUSTERED INDEX [IXC_DW_FTO_CRIME_VEICULO]
    ON [fipe_dw].[DW_FTO_CRIME_VEICULO]([COD_UF] ASC, [COD_ANO_MES] ASC);





