CREATE TABLE [fipe_ods].[ODS_DADOS_MODELO] (
    [COD_MES_REFERENCIA]   INT           NULL,
    [COD_MODELO]           INT           NULL,
    [COD_MARCA]            INT           NULL,
    [COD_TIPO_VEICULO]     INT           NULL,
    [COD_TIPO_COMBUSTIVEL] INT           NULL,
    [NUM_ANO_MODELO]       CHAR (5)      NULL,
    [VLR_MODELO]           MONEY         NULL,
    [DTA_INCLUSAO]         DATETIME2 (2) CONSTRAINT [DF_ODS_DADOS_MODELO_DTA_INCLUSAO] DEFAULT (getdate()) NULL,
    [DTA_ATUALIZACAO]      DATETIME2 (2) NULL,
    CONSTRAINT [FK_ODS_DADOS_MODELO_MARCA] FOREIGN KEY ([COD_MODELO]) REFERENCES [fipe_ods].[ODS_MODELO] ([COD_MODELO]),
    CONSTRAINT [FK_ODS_DADOS_MODELO_MODELO] FOREIGN KEY ([COD_MARCA]) REFERENCES [fipe_ods].[ODS_MARCA] ([COD_MARCA]),
    CONSTRAINT [FK_ODS_DADOS_MODELO_REFERENCIA] FOREIGN KEY ([COD_MES_REFERENCIA]) REFERENCES [fipe_ods].[ODS_MES_REFERENCIA] ([COD_MES_REFERENCIA])
);




GO
CREATE NONCLUSTERED INDEX [IXC_ODS_DADOS_MODELO]
    ON [fipe_ods].[ODS_DADOS_MODELO]([COD_MES_REFERENCIA] ASC, [COD_MODELO] ASC, [NUM_ANO_MODELO] ASC);


GO

GO